/* problem description:
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * Find the sum of all the even-valued terms in the sequence which do not exceed
 * four million.
 */

#include <stdio.h>

#define TRUE  1
#define FALSE 0

int main(void)
{
    int cur = 1, last = 1, sum = 0;
    
    while (TRUE)
    {
        printf("%d\n", cur);

        if ((cur % 2) == 0)
        {
            sum += cur;
            printf("Number %d is even. Sum now is %d\n", cur, sum);
        }

        if ((cur + last) > 4000000)
        {
            printf("Sum is %d\n", sum);
            return 0;
        }

        cur  += last;
        last = (cur - last);
    }
}
